In [2]:
import pandas as pd

subset of a DF

In [68]:
mydict = {
    'col1': [1,2,3,4],
    'col2' : [5,6,7,8],
    'col3' : ['one', 'two', 'three', 'four']
}

In [23]:
df = pd.DataFrame(mydict)
df

   col1  col2   col3
0     1     5    one
1     2     6    two
2     3     7  three
3     4     8   four

In [24]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [69]:
df.col1

0    1
1    2
2    3
3    4
Name: col1, dtype: int64

In [71]:
df.col2

0    5
1    6
2    7
3    8
Name: col2, dtype: int64

In [25]:
df.col3

0      one
1      two
2    three
3     four
Name: col3, dtype: object

In [10]:
df1 = df[['col1', 'col2']]
df1

   col1  col2
0     1     5
1     2     6
2     3     7
3     4     8

In [18]:
df[(df.col1 > 1) & (df['col2'] != 7)]

   col1  col2
1     2     6
3     4     8

In [26]:
# dipaly col3 is not equal to three
df[df.col3 != 'three']

   col1  col2  col3
0     1     5   one
1     2     6   two
3     4     8  four

slicing the df

In [32]:
df.iloc[0:3]

   col1  col2   col3
0     1     5    one
1     2     6    two
2     3     7  three

In [33]:
df.iloc[0:3]['col1']

0    1
1    2
2    3
Name: col1, dtype: int64

In [35]:
df.iloc[0:2][['col1', 'col2']]

   col1  col2
0     1     5
1     2     6

In [44]:
# find the col1 values greater than 2
df.loc[df['col1'] > 2]

   col1  col2   col3
2     3     7  three
3     4     8   four

Qurey menthod (str)

In [45]:
df.loc[0:3].query('col1 > 2')

   col1  col2   col3
2     3     7  three
3     4     8   four

In [47]:
df.query('2*col1 >= col2')

   col1  col2  col3
3     4     8  four

In [ ]:
df.query("col3 in ['three', 'four']")

# if we use single quote in brackets then use outer bracket double quote ["['']"]

   col1  col2   col3
2     3     7  three
3     4     8   four

In [54]:
df.query("col3 not in ['three', 'four']")

   col1  col2 col3
0     1     5  one
1     2     6  two

In [60]:
df.query("col2 != [5,7]")

   col1  col2  col3
1     2     6   two
3     4     8  four